### ISSUE TITLE
license of sha1sum.exe

### ISSUE THREAD

**Issue by matushorvath** [poweradminllc/PAExec#19]
The source code in GitHub includes sha1sum.exe, which seems to come from GNU Text Utilities and is covered by GNU GPL. This is causing issues when I try to use your software in corporate environment, since the PAExec license clearly cannot apply to sha1sum.exe, since it allows you to do more than GPL, and our intellectual property department has a hard time understanding that sha1sum.exe is not really a part of PAExec.

Would it be possible to address this somehow in the license, e.g. say the license does not apply to sha1sum.exe and GPL applies to that one file, or perhaps remove sha1sum.exe from the sources?

Thank you, and also thank you for providing your great software for free to everyone.

**Comment by poweradminllc** [comment]
Didn't notice that before.  It should not have been uploaded to the project at all as it is not used in any way.  It's been deleted.  Fixed!
