### ISSUE TITLE
Usage permission - can the code be modified

### ISSUE THREAD

**Issue by TinaLiao010** [poweradminllc/PAExec#23]
Hi 
Thanks for the great work. Power Admin tells us we could "anyone can use the software for private, public or commercial uses, including using it as part of a distributed commercial application"
https://www.poweradmin.com/paexec/paexec_eula.txt

But neither EULA nor any document tells we could modify the code, and then use the modified software "for private, public or commercial uses, including using it as part of a distributed commercial application".

May I ask, can we "modify" the code then use it as stated above?

Thanks a lot!

**Comment by dnebeker** [comment]
We've updated the EULA to indicate changing the source code is acceptable.  Also added a line item indicating the software cannot be used for illegal purposes (not directing that at you in any way).

**Comment by poweradminllc** [comment]
We've updated the EULA to indicate changing the source code is acceptable.  Also added a line item indicating the software cannot be used for illegal purposes (not directing that at you in any way).

**Comment by TinaLiao010** [comment]
Hi
Thanks for the quick reply. But two days passed, the EULA is still same with before. Have I got the wrong place?
https://www.poweradmin.com/paexec/paexec_eula.txt

**Comment by dnebeker** [comment]
Please check again - I see updated when viewing with the link you sent.

On Jun 27, 2017, at 9:35 PM, TinaLiao010 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi
Thanks for the quick reply. But two days passed, the EULA is still same with before. Have I got the wrong place?
https://www.poweradmin.com/paexec/paexec_eula.txt

**Comment by TinaLiao010** [comment]
Got it with many thanks!
