### ISSUE TITLE
Kill remote process while running via PAExec?

### ISSUE THREAD

**Issue by jheliker** [poweradminllc/PAExec#7]
Hello - 

This is not an issue per-se, rather a question. Is it possible to kill the remote process while it is still running, via PAExec? 

I'm executing some long-running processes, and sometimes it is desirable to be able to "cancel" -however killing PAExec doesn't stop the remote process.

Thanks for your help!
- James

**Comment by transistor1** [comment]
How about killing the process via the [taskkill](https://technet.microsoft.com/en-us/library/Bb491009.aspx) command?  That command can run on remote machines, or you could probably also issue it with paexec.

**Comment by poweradminllc** [comment]
Not an option for PAExec or PsExec so using taskkill will be required as transistor1 recommends.
